name: multi_generators
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  flutter_animate: ^4.5.0
  window_manager: ^0.3.8
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/

